[tool.poetry]
name = "ai-flow-back"
version = "0.6.0"
description = ""
authors = ["DahnM20 <you@example.com>"]
readme = "README.md"
packages = [{ include = "app" }]


[tool.poetry.dependencies]
python = ">=3.9,<3.12"
python-dotenv = "^1.0.0"
openai = "1.1.0"
flask = "^2.2.3"
flask-socketio = "^5.3.3"
flask-cors = "^3.0.10"
unstructured = "^0.6.3"
langchain = ">=0.0.303"
python-magic = "^0.4.14"
pytesseract = "^0.3.10"
requests = "^2.31.0"
tabulate = "^0.9.0"
pdf2image = "^1.16.3"
colorlog = "^6.7.0"
eventlet = "^0.33.3"
playwright = "1.39"
youtube-transcript-api = "^0.6.1"
pytube = "^15.0.0"
boto3 = "^1.28.52"
pyjwt = "^2.8.0"
jwcrypto = "^1.5.0"
python-jose = "^3.3.0"
cachetools = "^5.3.1"
flask-injector = "^0.15.0"
llama-index = "v0.9.46"
setuptools = "^68.2.2"
pypdf = "^3.16.4"
replicate = "0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
